### ISSUE TITLE
Feature: support creating .dgml on computer without Visual Studio installed

### ISSUE THREAD

**Issue by jawn** [marss19/reference-conflicts-analyzer#8]
Since reference conflicts may occur on a server without Visual Studio, e.g. a production server you don't have access to, it would be great to provide a stand alone version to generate the dgml file.

The dgml file can then be opened on a different machine where VS + DGML viewer is installed.

This could be a command line version or a GUI version.

If I understand correctly, this should be relatively straightforward. 
If my reasoning is ok, I could create a PR for a basic command line version.

**Comment by marss19** [comment]
Thank you for the suggestion, it is reasonable. I'll add this functionality. 



16 травня 2018, 15:29:34, від "Bernard Vander Beken" <notifications@github.com>: 


Since reference conflicts may occur on a server without Visual Studio, e.g. a production server you don't have access to, it would be great to provide a stand alone version to generate the dgml file.

The dgml file can then be opened on a different machine where VS + DGML viewer is installed.

This could be a command line version or a GUI version.

If I understand correctly, this should be relatively straightforward.
If my reasoning is ok, I could create a PR for a basic command line version.

**Comment by jawn** [comment]
Is the closing of this topic intented?

**Comment by marss19** [comment]
Yes. I added the feature.

**Comment by jawn** [comment]
Thanks! Is there a released version available for download?

**Comment by marss19** [comment]
Just added: https://github.com/marss19/reference-conflicts-analyzer/releases
